# Generated by Django 5.1.15 on 2026-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('low_stock', 'Xomashyo kam qoldi'), ('shop_limit_exceeded', "Do'kon limitidan oshdi"), ('order_priority', 'Shoshilinch buyurtma'), ('cash_handover', 'Pul topshirildi'), ('general', 'Umumiy')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('reference_model', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
