# Generated by Django 5.1.15 on 2026-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_add_sort_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('delivered_quantity__lte', models.F('quantity'))), name='orderitem_delivered_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__lte', models.F('delivered_quantity'))), name='orderitem_returned_lte_delivered'),
        ),
    ]
