# Generated by Django 5.2.6 on 2025-10-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_qop_user_salary_balance_user_weeks_worked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qop',
        ),
    ]
