# Generated by Django 5.2.6 on 2025-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('driver', 'Driver'), ('viewer', 'Viewer')], default='manager', max_length=20),
        ),
    ]
