# Generated by Django 5.2.6 on 2025-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_qop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weeks_worked',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('driver', 'Driver'), ('viewer', 'Viewer')], default='manager', max_length=20),
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
