# Generated by Django 5.2.6 on 2025-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_salary_balance_remove_user_weeks_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('driver', 'Driver'), ('viewer', 'Viewer'), ('nonvoy', 'Nonvoy')], default='manager', max_length=20),
        ),
    ]
