# Generated by Django 5.1.15 on 2026-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('default_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('production_salary_per_unit_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('meshok_size', models.DecimalField(decimal_places=3, default=160, max_digits=14)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
