# Generated by Django 5.1.15 on 2026-05-20 07:26

from django.db import migrations, models

# Sutli=1, Chap chap=3, Marokash Patir=5, then everything else alphabetically.
SORT_ORDER_MAP = {
    1: 10,  # Sutli
    3: 20,  # Chap chap
    5: 30,  # Marokash Patir
    6: 40,  # Sushka
}


def set_initial_sort_order(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.sort_order = SORT_ORDER_MAP.get(product.pk, 50)
        product.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_initial_sort_order, migrations.RunPython.noop),
    ]
