# Generated by Django 5.1.15 on 2026-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='communal_cost_per_unit_uzs',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Kommunal (gaz/svet) — 1 dona uchun, so'm. Tan narxiga qo'shiladi.", max_digits=16),
        ),
    ]
