# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('avg_cost_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_per_meshok', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='products.product')),
            ],
            options={
                'ordering': ['product', 'ingredient'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], default='UZS', max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='total_price / quantity — cached for cost calculations', max_digits=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_purchases', to='finance.kassaaccount')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
