# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shops.region'),
        ),
        migrations.AddField(
            model_name='shopproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_prices', to='products.product'),
        ),
        migrations.AddField(
            model_name='shopproductprice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['region', 'is_archived'], name='shops_shop_region__3e8c64_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['assigned_driver'], name='shops_shop_assigne_5c6307_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopproductprice',
            unique_together={('shop', 'product', 'currency')},
        ),
    ]
