# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('production', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrevisionreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='nonvoy',
            field=models.ForeignKey(limit_choices_to={'role': 'nonvoy'}, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='products.product'),
        ),
        migrations.AddField(
            model_name='productioningredientusage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='productioningredientusage',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='production.production'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['product', '-occurred_at'], name='production__product_206dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['nonvoy', '-occurred_at'], name='production__nonvoy__250662_idx'),
        ),
    ]
