# Generated by Django 5.1.15 on 2026-05-08 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
        ('users', '0003_employeegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='users.employeegroup'),
        ),
        migrations.AlterField(
            model_name='production',
            name='nonvoy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'nonvoy'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL),
        ),
    ]
