# Generated by Django 5.1.15 on 2026-08-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_inventoryrevisionreport_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrevisionreport',
            name='value_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
