# Generated by Django 5.2.6 on 2025-10-11 13:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_production_meshok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
