# Generated by Django 5.2.6 on 2025-10-20 17:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_low_stock_threshold'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBakeryProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_productions', to='products.product')),
            ],
            options={
                'verbose_name': 'Daily Bakery Production',
                'verbose_name_plural': 'Daily Bakery Productions',
                'ordering': ['-date'],
            },
        ),
    ]
