# Generated by Django 5.2.6 on 2025-10-20 17:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_dailybakeryproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
