# Generated by Django 5.2.6 on 2025-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bakeryproductstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproductstock',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
