# Generated by Django 5.2.6 on 2025-10-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bakeryproductstock_pinned'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryproductstock',
            name='product_name',
        ),
        migrations.AddField(
            model_name='bakeryproductstock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bakery_stocks', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakeryproductstock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
