# Generated by Django 5.2.6 on 2025-11-04 14:35

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_bakeryproductstock_product_name_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybakeryproduction',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='When confirmed the daily production is locked.'),
        ),
        migrations.AlterField(
            model_name='dailybakeryproduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailybakeryproduction',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterUniqueTogether(
            name='dailybakeryproduction',
            unique_together={('product', 'date')},
        ),
    ]
