# Generated by Django 5.2.6 on 2025-10-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
