# Generated by Django 5.2.6 on 2025-10-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_purchase_unit_price_purchase_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='unit_price',
        ),
    ]
