# Generated by Django 5.2.6 on 2025-10-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_price_purchase_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
