# Generated by Django 5.2.6 on 2025-10-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0, help_text='Shop’s outstanding debt (qarzdorlik)', max_digits=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.region')),
            ],
            options={
                'verbose_name': 'Do‘kon',
                'verbose_name_plural': 'Do‘konlar',
            },
        ),
    ]
