# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_type', models.CharField(choices=[('per_unit', 'Dona boshi'), ('per_meshok', 'Meshok boshi'), ('per_week', 'Haftalik'), ('fixed_monthly', "Oylik qat'iy"), ('per_product', "Mahsulot bo'yicha")], max_length=20)),
                ('currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], default='UZS', max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, help_text='Pre-system debt owed to or by employee (positive = we owe them).', max_digits=16)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('salary', 'Oylik'), ('advance', 'Avans (oldindan)'), ('bonus', 'Bonus / ustama'), ('deduction', 'Ushlab qolish')], default='salary', max_length=20)),
                ('currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], default='UZS', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='finance.kassaaccount')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
