# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['user', '-occurred_at'], name='salary_sala_user_id_4ad7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['kind', '-occurred_at'], name='salary_sala_kind_136e6d_idx'),
        ),
    ]
