# Generated by Django 5.1.15 on 2026-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
