# Generated by Django 5.1.15 on 2026-06-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_salarypayment_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrate',
            name='reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
