# Generated by Django 5.1.15 on 2026-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salaryrate_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrate',
            name='week_start_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], help_text='Haftalik ish haqi uchun hafta boshlanadigan kun.', null=True),
        ),
    ]
