# Generated by Django 5.1.15 on 2026-09-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_salarypayment_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_type', models.CharField(choices=[('per_unit', 'Dona boshi'), ('per_meshok', 'Meshok boshi'), ('per_week', 'Haftalik'), ('fixed_monthly', "Oylik qat'iy"), ('per_product', "Mahsulot bo'yicha")], max_length=20)),
                ('currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], default='UZS', max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('week_start_day', models.IntegerField(blank=True, choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'effective_from'],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='salary_sala_user_id_666a00_idx')],
            },
        ),
    ]
