# Generated by Django 5.1.15 on 2026-09-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_communal_per_meshok_and_other'),
        ('salary', '0008_seed_rate_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_per_meshok_uzs', models.DecimalField(decimal_places=2, default=0, help_text="Shu ishchi shu mahsulotdan 1 qop (meshok) uchun oladigan summa, so'm.", max_digits=16)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rates', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'product__sort_order', 'product__name'],
                'indexes': [models.Index(fields=['user', 'product'], name='salary_user_user_id_a2bccc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uniq_user_product_rate')],
            },
        ),
    ]
