# Generated by Django 5.2.6 on 2025-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
