# Generated by Django 5.2.6 on 2025-10-16 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salarypayment_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrate',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Oldindan hisoblangan maosh (sistemadan oldingi qarzdorlik)', max_digits=14),
        ),
    ]
