# Generated by Django 5.1.15 on 2026-04-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='produced_product',
            field=models.ForeignKey(blank=True, help_text='For nonvoy staff: which product this baker produces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='products.product'),
        ),
    ]
