# Generated by Django 5.1.15 on 2026-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employeegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
