# Generated by Django 5.2.6 on 2025-11-02 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Olingan summa'),
        ),
    ]
