# Generated by Django 5.2.6 on 2025-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivered_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
