# Generated by Django 5.2.6 on 2025-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Kutilmoqda'), ('Partially Delivered', 'Qisman yetkazilgan'), ('Delivered', 'Yetkazilgan')], default='Pending', max_length=30),
        ),
    ]
