# Generated by Django 5.1.15 on 2026-04-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhandover',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.expensecategory'),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_expenses', to='finance.kassaaccount'),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='finance.kassaaccount'),
        ),
        migrations.AddField(
            model_name='kassatransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.kassaaccount'),
        ),
        migrations.AddField(
            model_name='kassatransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(help_text='Which kassa received this money', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.kassaaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Feature #20 — who received the cash (driver/cashier)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='cashhandover',
            index=models.Index(fields=['driver', '-occurred_at'], name='finance_cas_driver__7ac581_idx'),
        ),
        migrations.AddIndex(
            model_name='kassatransaction',
            index=models.Index(fields=['account', '-occurred_at'], name='finance_kas_account_15f2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='kassatransaction',
            index=models.Index(fields=['kind', '-occurred_at'], name='finance_kas_kind_82e9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='kassatransaction',
            index=models.Index(fields=['reference_model', 'reference_id'], name='finance_kas_referen_a88e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['shop', '-received_at'], name='finance_pay_shop_id_bcd3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collected_by', '-received_at'], name='finance_pay_collect_76aab6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', '-received_at'], name='finance_pay_payment_6ed622_idx'),
        ),
    ]
