# Generated by Django 5.1.15 on 2026-06-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_kassatransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kassatransaction',
            name='kind',
            field=models.CharField(choices=[('payment_in', "Kirim (to'lov)"), ('loan_repayment', "Qarz to'lovi"), ('inventory_purchase', 'Xomashyo xarid'), ('general_expense', 'Umumiy xarajat'), ('salary', 'Oylik'), ('advance', 'Avans'), ('bonus', 'Bonus'), ('cash_handover', 'Pul topshirish'), ('adjustment', "Qo'lda tuzatish"), ('transfer', 'Kassalar orasida'), ('exchange', 'Valyuta ayirboshlash')], max_length=32),
        ),
        migrations.CreateModel(
            name='KassaExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], max_length=3)),
                ('to_currency', models.CharField(choices=[('UZS', "UZS (so'm)"), ('USD', 'USD (dollar)')], max_length=3)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='finance.kassaaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
