# Generated by Django 5.1.15 on 2026-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_kassatransaction_kind_kassaexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='include_in_pnl',
            field=models.BooleanField(default=True, help_text="Agar o'chirilsa, bu kategoriya Hisobotlar P&L xarajatlariga kirmaydi."),
        ),
    ]
